services:
  67design:
    container_name: 67design
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    # env_file:
    #   - ../.env
    ports:
      - "3018:3000"
    networks:
      - caddy-network

networks:
  caddy-network:
    driver: bridge
    attachable: true
